blank_issues_enabled: false
contact_links:
  - name: ğŸ–¥ï¸ Manga Akojdad website
    url: https://www.instagram.com/emperor_._1?igsh=enM4aG55Nmwwdmx2 https://manga-akojdad.example.com/
    about: Guides, troubleshooting, and answers to common questions